title: Mohaimin Ehsan
logo: /assets/img/logo.png
description: I am seeking a challenging and rewarding position in software development where I can leverage my educational qualifications, experience, creativity, and hard work to make a meaningful contribution. My goal is to build a successful career as an IT professional and contribute to research in the field. I am a dedicated, loyal, and hardworking individual who is committed to achieving excellence in everything I do.
show_downloads: false
theme: jekyll-theme-minimal
