title: Mohaimin Ehsan
logo: /assets/img/logo.png
description: The desire for a responsible position to contribute effectively in the field of software development through optimal
utilization of educational qualification, experience, creativity and hard work. Finally, to build a career as a successful IT
Professional and participate in advanced research in the concerned fields.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
